name: Percy

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Percy Test
        run: npx percy exec -- yarn percy

        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}